let state={session:null,records:[],currentAnimal:{},activeFieldIndex:0};
const classNames={H:"Maiden Heifer",F:"First Lactation Heifer",W:"Wet Cow",D:"Dry Cow",C:"Cull for Age Cow"};
const fieldDefinitions=[
{key:"classCode",label:"CLASS",enabled:s=>s.recordClass,fixed:s=>s.fixedClass||null,prompt:"ENTER CLASS",validate:validateClass,display:v=>classNames[v]||v},
{key:"age",label:"AGE",enabled:s=>s.recordAge,fixed:s=>null,prompt:"ENTER AGE",validate:validateAge,display:v=>v},
{key:"bcs",label:"BCS",enabled:s=>s.recordBCS,fixed:s=>null,prompt:"ENTER BCS",validate:validateBCS,display:v=>v},
{key:"preg",label:"PREGNANCY",enabled:s=>s.recordPreg,fixed:s=>null,prompt:"ENTER PREGNANCY",validate:validatePreg,display:v=>v},
{key:"weight",label:"WEIGHT",enabled:s=>s.recordWeight,fixed:s=>null,prompt:"ENTER WEIGHT",validate:validateWeight,display:v=>v?`${v} kg`:""},
{key:"wetDry",label:"WET / DRY",enabled:s=>s.recordWetDry,fixed:s=>s.fixedWetDry||null,prompt:"ENTER WET / DRY",validate:validateWetDry,display:v=>v}
];
function loadState(){const saved=localStorage.getItem("cvsStationStatsV03");if(saved)state=JSON.parse(saved);if(!state.currentAnimal)state.currentAnimal={};updateUI();}
function saveState(){localStorage.setItem("cvsStationStatsV03",JSON.stringify(state));updateUI();}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");if(id==="crush")setTimeout(()=>document.getElementById("quickInput").focus(),100);}
function startSession(){state.session={id:crypto.randomUUID(),stationName:document.getElementById("stationName").value||"Unnamed Station",paddockName:document.getElementById("paddockName").value||"",operatorName:document.getElementById("operatorName").value||"",sessionDate:document.getElementById("sessionDate").value||new Date().toISOString().slice(0,10),recordClass:document.getElementById("recordClass").checked,recordAge:document.getElementById("recordAge").checked,recordBCS:document.getElementById("recordBCS").checked,recordPreg:document.getElementById("recordPreg").checked,recordWeight:document.getElementById("recordWeight").checked,recordWetDry:document.getElementById("recordWetDry").checked,fixedClass:document.getElementById("fixedClass").value,fixedWetDry:document.getElementById("fixedWetDry").value};state.records=[];resetCurrentAnimal();saveState();showScreen("crush");setStatus("Session started. Follow the orange box.",false);}
function enabledFields(){if(!state.session)return[];return fieldDefinitions.filter(f=>f.enabled(state.session)||f.fixed(state.session));}
function resetCurrentAnimal(){state.currentAnimal={id:crypto.randomUUID(),timestamp:new Date().toISOString()};for(const f of fieldDefinitions){const fixedValue=state.session?f.fixed(state.session):null;state.currentAnimal[f.key]=fixedValue||null;}state.activeFieldIndex=nextIncompleteIndex();}
function nextIncompleteIndex(){const fields=enabledFields();for(let i=0;i<fields.length;i++){if(!state.currentAnimal||state.currentAnimal[fields[i].key]===null||state.currentAnimal[fields[i].key]==="")return i;}return fields.length;}
const quickInput=document.getElementById("quickInput");
quickInput.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();handleEntry(quickInput.value.trim().toUpperCase());quickInput.value="";}if(e.key==="F1"){e.preventDefault();undoLastAnimal();}if(e.key==="Backspace"&&quickInput.value===""){e.preventDefault();clearCurrentField();}});
function handleEntry(value){if(!state.session)return setStatus("Start a session first.",true);const fields=enabledFields();state.activeFieldIndex=nextIncompleteIndex();if(state.activeFieldIndex>=fields.length){saveCurrentAnimal();return;}const field=fields[state.activeFieldIndex];if(!value)return setStatus(`${field.prompt}: no value entered`,true);const result=field.validate(value);if(!result.ok)return setStatus(result.message,true);state.currentAnimal[field.key]=result.value;state.activeFieldIndex=nextIncompleteIndex();if(state.activeFieldIndex>=fields.length){saveCurrentAnimal();}else{beep(650);setStatus(`Recorded ${field.label}: ${field.display(result.value)}`,false);saveState();}}
function saveCurrentAnimal(){const r={...state.currentAnimal,sessionId:state.session.id,stationName:state.session.stationName,paddockName:state.session.paddockName,timestamp:new Date().toISOString()};r.draft=assignDraft(r);state.records.push(r);beep(950);flashScreen();setStatus(`SAVED ✔ Animal #${state.records.length} | ${classNames[r.classCode]||r.classCode||""} | ${r.preg||""} | ${r.draft}`,false,true);resetCurrentAnimal();saveState();}
function clearCurrentField(){const fields=enabledFields();const idx=nextIncompleteIndex();const previous=Math.max(0,idx-1);const field=fields[previous];if(!field)return;if(field.fixed(state.session))return;state.currentAnimal[field.key]=null;state.activeFieldIndex=previous;setStatus(`Cleared ${field.label}`,true);saveState();}
function undoLastAnimal(){if(!state.records.length)return setStatus("No animal to undo.",true);const removed=state.records.pop();beep(250);setStatus(`Undid last animal: ${classNames[removed.classCode]||removed.classCode||""} ${removed.preg||""}`,true);saveState();}
function validateClass(v){if(!["H","F","W","D","C"].includes(v))return{ok:false,message:"Class must be H, F, W, D, or C"};return{ok:true,value:v};}
function validateAge(v){const n=Number(v);if(!Number.isInteger(n)||n<0||n>9)return{ok:false,message:"Age must be 0-9"};return{ok:true,value:n};}
function validateBCS(v){const n=Number(v);if(![1,2,3,4,5].includes(n))return{ok:false,message:"BCS must be 1-5"};return{ok:true,value:n};}
function validatePreg(v){if(v==="E")return{ok:true,value:"E"};if(/^[1-9]$/.test(v))return{ok:true,value:"P"+v};if(/^P[1-9]$/.test(v))return{ok:true,value:v};return{ok:false,message:"Pregnancy must be E or 1-9"};}
function validateWeight(v){const n=Number(v);if(!n||n<=0)return{ok:false,message:"Weight must be a number"};return{ok:true,value:n};}
function validateWetDry(v){if(["W","WET"].includes(v))return{ok:true,value:"Wet"};if(["D","DRY"].includes(v))return{ok:true,value:"Dry"};return{ok:false,message:"Wet/Dry must be W or D"};}
function pregNumber(p){if(!p||p==="E")return 0;return Number(p.replace("P",""));}
function assignDraft(r){const p=pregNumber(r.preg);if(r.classCode==="C")return"Draft 5 - Cull for age";if(["H","F"].includes(r.classCode)&&r.preg==="E")return"Draft 1 - Empty heifers";if(["H","F"].includes(r.classCode)&&p>=1&&p<=3)return"Draft 2 - P1-P3 heifers";if(["H","F"].includes(r.classCode)&&p>=4&&p<=6)return"Draft 3 - P4-P6 heifers";if(["H","F"].includes(r.classCode)&&p>=7&&p<=9)return"Draft 4 - P7-P9 heifers";return"Draft 6 - Other cows";}
function beep(freq){try{const ctx=new(window.AudioContext||window.webkitAudioContext)();const osc=ctx.createOscillator();osc.connect(ctx.destination);osc.frequency.value=freq;osc.start();osc.stop(ctx.currentTime+.1);}catch(e){}}
function flashScreen(){const el=document.getElementById("screenFlash");el.classList.remove("flash");void el.offsetWidth;el.classList.add("flash");setTimeout(()=>el.classList.remove("flash"),1200);}
function setStatus(msg,error,flash=false){const el=document.getElementById("status");el.textContent=msg;el.className="status "+(error?"error":"saved")+(flash?" readyFlash":"");if(error)beep(220);setTimeout(()=>el.classList.remove("readyFlash"),1100);}
function updateUI(){const s=state.session;document.getElementById("totalCount").textContent=state.records.length;document.getElementById("currentAnimalNo").textContent=state.records.length+1;document.getElementById("sessionBanner").textContent=s?`${s.stationName} | ${s.paddockName} | ${s.sessionDate}`:"No active session";renderFieldStack();renderLiveStats();}
function renderFieldStack(){const container=document.getElementById("fieldStack");const prompt=document.getElementById("megaPrompt");if(!state.session){container.innerHTML="";prompt.textContent="START SESSION";return;}const fields=enabledFields();const active=nextIncompleteIndex();container.innerHTML=fields.map((f,idx)=>{const val=state.currentAnimal?state.currentAnimal[f.key]:null;const done=val!==null&&val!=="";const icon=done?"✅":(idx===active?"➡️":"⬜");const css=done?"done":(idx===active?"current":"waiting");return `<div class="fieldBox ${css}"><div class="fieldLabel">${f.label}</div><div class="fieldValue">${done?f.display(val):"WAITING"}</div><div class="fieldIcon">${icon}</div></div>`;}).join("");prompt.textContent=active>=fields.length?"PRESS ENTER TO SAVE":fields[active].prompt;}
function renderLiveStats(){const total=state.records.length;const empty=state.records.filter(r=>r.preg==="E").length;const pregnant=state.records.filter(r=>r.preg&&r.preg!=="E").length;document.getElementById("pregnantCount").textContent=pregnant;document.getElementById("emptyCount").textContent=empty;document.getElementById("pregPercent").textContent=total?`${Math.round((pregnant/total)*100)}%`:"0%";const draftCounts=groupCount(state.records,r=>r.draft);const draftOrder=["Draft 1 - Empty heifers","Draft 2 - P1-P3 heifers","Draft 3 - P4-P6 heifers","Draft 4 - P7-P9 heifers","Draft 5 - Cull for age","Draft 6 - Other cows"];document.getElementById("draftTallies").innerHTML=draftOrder.map(d=>`<div class="draftItem"><b>${draftCounts[d]||0}</b> ${d}</div>`).join("");const last=state.records.slice(-5).reverse();document.getElementById("lastAnimals").innerHTML=last.map((r,idx)=>`<div class="lastItem">#${state.records.length-idx} ✅ ${classNames[r.classCode]||r.classCode||""} Age ${r.age??"-"} BCS ${r.bcs??"-"} ${r.preg??""} ${r.weight?r.weight+"kg":""}</div>`).join("");}
function clearAllData(){if(confirm("Clear all cattle records and current session?")){state={session:null,records:[],currentAnimal:{},activeFieldIndex:0};localStorage.removeItem("cvsStationStatsV03");location.reload();}}
function exportCSV(){const rows=[["Station","Paddock","DateTime","Class","Age","BCS","Pregnancy","Weight","WetDry","Draft"]];state.records.forEach(r=>rows.push([r.stationName,r.paddockName,r.timestamp,classNames[r.classCode]||r.classCode,r.age??"",r.bcs??"",r.preg??"",r.weight??"",r.wetDry??"",r.draft??""]));const csv=rows.map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${state.session?.stationName||"session"}_station_stats.csv`;a.click();}
function groupCount(records,keyFn){const out={};records.forEach(r=>{const k=keyFn(r)||"Unknown";out[k]=(out[k]||0)+1;});return out;}
function average(arr){const vals=arr.filter(v=>v!==null&&v!==undefined&&!isNaN(v));if(!vals.length)return null;return vals.reduce((a,b)=>a+b,0)/vals.length;}
let chartObjects=[];function clearCharts(){chartObjects.forEach(c=>c.destroy());chartObjects=[];}
function chart(id,type,labels,data,label){const ctx=document.getElementById(id);chartObjects.push(new Chart(ctx,{type,data:{labels,datasets:[{label,data}]},options:{responsive:true,scales:type==="bar"?{y:{beginAtZero:true}}:{}}}));}
function pregOrderLabels(){return["E","P1","P2","P3","P4","P5","P6","P7","P8","P9"];}
function generateCharts(){clearCharts();const records=state.records;const pregLabels=pregOrderLabels();const pregCounts=groupCount(records,r=>r.preg);chart("pregChart","bar",pregLabels,pregLabels.map(l=>pregCounts[l]||0),"Pregnancy stage histogram");const bcsLabels=["1","2","3","4","5"];const bcsCounts=groupCount(records,r=>r.bcs);chart("bcsChart","bar",bcsLabels,bcsLabels.map(l=>bcsCounts[l]||0),"BCS histogram");const draftCounts=groupCount(records,r=>r.draft);chart("draftChart","bar",Object.keys(draftCounts),Object.values(draftCounts),"Draft tally");const classCounts=groupCount(records,r=>classNames[r.classCode]||r.classCode);chart("classChart","bar",Object.keys(classCounts),Object.values(classCounts),"Animal class breakdown");const heifers=records.filter(r=>["H","F"].includes(r.classCode));const weightByPreg=pregLabels.map(p=>average(heifers.filter(r=>r.preg===p).map(r=>r.weight))||0);chart("heiferWeightPregChart","bar",pregLabels,weightByPreg,"Heifers: average weight by pregnancy stage");const bcsByPreg=pregLabels.map(p=>average(records.filter(r=>r.preg===p).map(r=>r.bcs))||0);chart("bcsPregChart","bar",pregLabels,bcsByPreg,"Average BCS by pregnancy stage");buildSummary();}
function buildSummary(){const total=state.records.length;const empty=state.records.filter(r=>r.preg==="E").length;const pregnant=state.records.filter(r=>r.preg&&r.preg!=="E").length;const avgBCS=average(state.records.map(r=>r.bcs));const heifers=state.records.filter(r=>["H","F"].includes(r.classCode));const avgHeiferWeight=average(heifers.map(r=>r.weight));document.getElementById("reportSummary").innerHTML=`<h3>${state.session?.stationName||""} — ${state.session?.paddockName||""}</h3><p><b>Total:</b> ${total} head</p><p><b>Pregnant:</b> ${pregnant} (${total?Math.round(pregnant/total*100):0}%)</p><p><b>Empty:</b> ${empty} (${total?Math.round(empty/total*100):0}%)</p><p><b>Average BCS:</b> ${avgBCS?avgBCS.toFixed(2):"N/A"}</p><p><b>Average heifer weight:</b> ${avgHeiferWeight?avgHeiferWeight.toFixed(1)+" kg":"N/A"}</p>`;}
async function exportPDF(){generateCharts();const{jsPDF}=window.jspdf;const pdf=new jsPDF("p","mm","a4");const logo=await imageToDataURL("image.png");if(logo)pdf.addImage(logo,"PNG",15,10,35,35);pdf.setFontSize(18);pdf.text("Central Vets Station Stats",55,20);pdf.setFontSize(12);pdf.text("Built by vets. Designed for stations.",55,28);pdf.text("Cattle Pregnancy Testing Report",55,36);pdf.setFontSize(11);pdf.text(`Station: ${state.session?.stationName||""}`,15,55);pdf.text(`Paddock: ${state.session?.paddockName||""}`,15,62);pdf.text(`Date: ${state.session?.sessionDate||""}`,15,69);pdf.text(`Operator: ${state.session?.operatorName||""}`,15,76);const total=state.records.length;const empty=state.records.filter(r=>r.preg==="E").length;const pregnant=state.records.filter(r=>r.preg&&r.preg!=="E").length;const avgBCS=average(state.records.map(r=>r.bcs));pdf.text(`Total: ${total} head`,15,90);pdf.text(`Pregnant: ${pregnant} (${total?Math.round(pregnant/total*100):0}%)`,15,97);pdf.text(`Empty: ${empty} (${total?Math.round(empty/total*100):0}%)`,15,104);pdf.text(`Average BCS: ${avgBCS?avgBCS.toFixed(2):"N/A"}`,15,111);const chartIds=["pregChart","bcsChart","draftChart","classChart","heiferWeightPregChart","bcsPregChart"];let y=122;for(const id of chartIds){const canvas=document.getElementById(id);const img=canvas.toDataURL("image/png",1.0);if(y>225){pdf.addPage();y=15;}pdf.addImage(img,"PNG",15,y,180,75);y+=85;}pdf.save(`${state.session?.stationName||"station"}_station_stats_report.pdf`);}
function imageToDataURL(src){return new Promise(resolve=>{const img=new Image();img.crossOrigin="anonymous";img.onload=function(){const canvas=document.createElement("canvas");canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext("2d");ctx.drawImage(img,0,0);resolve(canvas.toDataURL("image/png"));};img.onerror=()=>resolve(null);img.src=src;});}
document.getElementById("sessionDate").value=new Date().toISOString().slice(0,10);loadState();
