const App=(()=>{const KEY="CVSS_V20";
const classNames={H:"Maiden heifer",F:"First-lactation heifer",W:"Wet cow",D:"Dry cow",C:"Cull cow",S:"Speyed cow",B:"Bull"};
let S={profiles:[],sessions:[],tallies:[],draftTemplates:[],active:null,records:[],animal:{},tally:{},draftPens:[]};
let charts=[];
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID();
const pct=(n,d)=>d?Math.round(n/d*100):0;
const avg=a=>{let v=a.filter(x=>x!==null&&x!==undefined&&!isNaN(x));return v.length?v.reduce((x,y)=>x+y,0)/v.length:null};
const pregNo=p=>!p||p==="E"?0:Number(String(p).replace("P",""));
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const load=()=>{let raw=localStorage.getItem(KEY);if(raw)S=JSON.parse(raw);S.profiles??=[];S.sessions??=[];S.tallies??=[];S.draftTemplates??=[];S.records??=[];S.tally??={};S.draftPens??=[];};

function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");if(id==="crush")setTimeout(()=>$("quickInput").focus(),50);if(id==="tally")renderTally();if(id==="library")renderLibrary();if(id==="report")renderReport();if(id==="session"){renderDraftTemplates();renderDraftPens();renderCalvingGuide();}}
function profile(st){return S.profiles.find(p=>(p.name||"").toLowerCase()===(st||"").toLowerCase())}
function riskText(p){let a=[];if(["Likely deficient","Likely marginal"].includes(p.phos))a.push("Phosphorus/nutrition risk flag.");if(["Moderate","High"].includes(p.dryFeed))a.push("Dry-season feed risk flag.");if(p.country==="Northern Forest")a.push("Northern Forest: monitor lactating cow BCS and re-conception closely.");return a.join(" ")||"No major profile risk flags set."}
function profileHTML(p){return `<h3>${p.name}</h3><p><b>${p.country}</b> | ${p.size} | ${p.total||"?"} cattle | ${p.breeders||"?"} breeders | ${p.breed||""}</p><p>Production: heifers +${p.heiferGrowth||0}kg/yr, cows +${p.cowGrowth||0}kg/yr, dry BCS ${p.dryBcs||0}/yr, wet BCS ${p.wetBcs||0}/yr, puberty target ${p.puberty||"?"}kg.</p><p>${riskText(p)}</p>`}
function saveProfile(){let p={id:uid(),name:pfName.value||"Unnamed Station",manager:pfManager.value,region:pfRegion.value,country:pfCountry.value,size:pfSize.value,total:+pfTotal.value||0,breeders:+pfBreeders.value||0,breed:pfBreed.value,joining:pfJoining.value,phos:pfPhos.value,dryFeed:pfDryFeed.value,weaning:pfWeaning.value,heiferGrowth:+pfHeiferGrowth.value||0,cowGrowth:+pfCowGrowth.value||0,dryBcs:+pfDryBcs.value||0,wetBcs:+pfWetBcs.value||0,puberty:+pfPuberty.value||0,targetBcs:+pfTargetBcs.value||3,notes:pfNotes.value,updatedAt:new Date().toISOString()};S.profiles=S.profiles.filter(x=>x.name.toLowerCase()!=p.name.toLowerCase());S.profiles.unshift(p);save();profileOut.innerHTML=profileHTML(p);completeSound();}
function openProfile(id){let p=S.profiles.find(x=>x.id===id);if(!p)return;pfName.value=p.name;pfManager.value=p.manager;pfRegion.value=p.region;pfCountry.value=p.country;pfSize.value=p.size;pfTotal.value=p.total;pfBreeders.value=p.breeders;pfBreed.value=p.breed;pfJoining.value=p.joining;pfPhos.value=p.phos;pfDryFeed.value=p.dryFeed;pfWeaning.value=p.weaning;pfHeiferGrowth.value=p.heiferGrowth;pfCowGrowth.value=p.cowGrowth;pfDryBcs.value=p.dryBcs;pfWetBcs.value=p.wetBcs;pfPuberty.value=p.puberty;pfTargetBcs.value=p.targetBcs;pfNotes.value=p.notes;profileOut.innerHTML=profileHTML(p);show("profile")}
function applyProfileToSession(){if(profile(ssStation.value)){ssYear.value ||= new Date().getFullYear();}}

function selected(id){return Array.from($(id).selectedOptions).map(o=>o.value)}
function renderDraftTemplates(){draftTemplate.innerHTML='<option value="">Manual / none</option>'+S.draftTemplates.map(t=>`<option value="${t.id}">${t.name}</option>`).join("")}
function addDraftPen(){let pen={id:uid(),name:draftName.value||`Pen ${S.draftPens.length+1}`,classes:selected("draftClasses"),wetDry:draftWetDry.value,pregs:selected("draftPregs")};if(!pen.classes.length&&!pen.pregs.length&&pen.wetDry==="ANY"){alert("Pick at least one class, wet/dry filter or preg stage.");return}S.draftPens.push(pen);draftName.value="";save();renderDraftPens()}
function renderDraftPens(){draftPens.innerHTML=S.draftPens.length?S.draftPens.map((p,i)=>`<div class="draftPenItem"><b>${i+1}. ${p.name}</b><br>Classes: ${p.classes.map(c=>classNames[c]).join(", ")||"Any"}<br>Wet/Dry: ${p.wetDry}<br>Preg: ${p.pregs.join(", ")||"Any"} <button onclick="App.removeDraftPen('${p.id}')">Remove</button></div>`).join(""):"No pens selected.";renderCalvingGuide()}
function removeDraftPen(id){S.draftPens=S.draftPens.filter(p=>p.id!==id);save();renderDraftPens()}
function clearDraftPens(){S.draftPens=[];save();renderDraftPens()}
function loadDraftExample(type){S.draftPens=type==="heifers"?[{id:uid(),name:"Pen 1 - Empty heifers",classes:["H","F"],wetDry:"ANY",pregs:["E"]},{id:uid(),name:"Pen 2 - P1-P3 heifers",classes:["H","F"],wetDry:"ANY",pregs:["P1","P2","P3"]},{id:uid(),name:"Pen 3 - P4-P6 heifers",classes:["H","F"],wetDry:"ANY",pregs:["P4","P5","P6"]},{id:uid(),name:"Pen 4 - P7-P9 heifers",classes:["H","F"],wetDry:"ANY",pregs:["P7","P8","P9"]}]:[{id:uid(),name:"Pen 1 - Wet empty cows + dry P8-P9",classes:["W","D"],wetDry:"ANY",pregs:["E","P8","P9"]},{id:uid(),name:"Pen 2 - Dry P1-P6 cows",classes:["D"],wetDry:"ANY",pregs:["P1","P2","P3","P4","P5","P6"]},{id:uid(),name:"Pen 3 - Wet P1-P7 cows",classes:["W"],wetDry:"ANY",pregs:["P1","P2","P3","P4","P5","P6","P7"]},{id:uid(),name:"Pen 4 - Speyed cows / bulls / culls",classes:["S","B","C"],wetDry:"ANY",pregs:[]}];save();renderDraftPens()}
function saveDraftTemplate(){if(!S.draftPens.length){alert("No pens to save.");return}let name=prompt("Template name","Draft template");if(!name)return;S.draftTemplates.unshift({id:uid(),name,pens:JSON.parse(JSON.stringify(S.draftPens))});save();renderDraftTemplates()}
function loadDraftTemplate(){let t=S.draftTemplates.find(x=>x.id===draftTemplate.value);if(!t)return;S.draftPens=JSON.parse(JSON.stringify(t.pens)).map(p=>({...p,id:uid()}));save();renderDraftPens()}

function addMonths(d,m){let x=new Date(d);x.setMonth(x.getMonth()+m);return x}
function month(d){return d.toLocaleDateString("en-AU",{month:"short",year:"numeric"})}
function monthsToCalving(p){return p==="E"?null:Math.max(0,10-pregNo(p))}
function calvingWindow(p,d=ssDate.value||today()){if(p==="E")return"Empty";let m=monthsToCalving(p);return `${month(addMonths(d,m))}–${month(addMonths(d,m+1))}`}
function renderCalvingGuide(){if(!window.calvingGuide)return;let stages=["E","P1","P2","P3","P4","P5","P6","P7","P8","P9"];calvingGuide.innerHTML="<h4>Calving guide for draft splits</h4>"+stages.map(s=>`<div><b>${s}</b>: ${calvingWindow(s)}</div>`).join("")}

const fields=[{k:"classCode",label:"CLASS",on:s=>s.recClass,fixed:s=>s.fixClass,prompt:"ENTER CLASS",hint:"H/F/W/D/C/S/B",auto:true,val:v=>["H","F","W","D","C","S","B"].includes(v)?v:null,disp:v=>classNames[v]},{k:"age",label:"AGE",on:s=>s.recAge,fixed:s=>null,prompt:"ENTER AGE",hint:"0-9",auto:true,val:v=>/^[0-9]$/.test(v)?+v:null,disp:v=>v},{k:"bcs",label:"BCS",on:s=>s.recBCS,fixed:s=>null,prompt:"ENTER BCS 1-5",hint:"1-5",auto:true,val:v=>/^[1-5]$/.test(v)?+v:null,disp:v=>v},{k:"preg",label:"PREG",on:s=>s.recPreg,fixed:s=>null,prompt:"ENTER PREG P1-P9",hint:"E or 1-9",auto:true,val:v=>v==="E"?"E":(/^[1-9]$/.test(v)?"P"+v:/^P[1-9]$/.test(v)?v:null),disp:v=>v},{k:"weight",label:"WEIGHT",on:s=>s.recWeight,fixed:s=>null,prompt:"ENTER WEIGHT",hint:"kg + Enter",auto:false,val:v=>+v>0?+v:null,disp:v=>`${v}kg`},{k:"wetDry",label:"WET/DRY",on:s=>s.recWetDry,fixed:s=>s.fixWetDry,prompt:"ENTER WET/DRY",hint:"W or D",auto:true,val:v=>["W","WET"].includes(v)?"Wet":["D","DRY"].includes(v)?"Dry":null,disp:v=>v}];
function activeFields(){let s=S.active;return fields.filter(f=>f.on(s)||f.fixed(s))}
function resetAnimal(){S.animal={id:uid(),time:new Date().toISOString()};fields.forEach(f=>S.animal[f.k]=S.active?f.fixed(S.active)||null:null)}
function nextIdx(){let af=activeFields();for(let i=0;i<af.length;i++)if(S.animal[af[i].k]===null||S.animal[af[i].k]==="")return i;return af.length}
function startSession(){let p=profile(ssStation.value);S.active={id:uid(),station:ssStation.value||"Unnamed Station",year:+ssYear.value||new Date().getFullYear(),paddock:ssPaddock.value,mob:ssMob.value,operator:ssOperator.value,date:ssDate.value||today(),profile:p?.id||null,country:p?.country||"",recClass:recClass.checked,recAge:recAge.checked,recBCS:recBCS.checked,recPreg:recPreg.checked,recWeight:recWeight.checked,recWetDry:recWetDry.checked,fixClass:fixClass.value,fixWetDry:fixWetDry.value,draftPens:JSON.parse(JSON.stringify(S.draftPens))};S.records=[];resetAnimal();save();show("crush");renderCrush()}
function assignDraft(r){for(let p of S.active.draftPens||[]){let okC=!p.classes.length||p.classes.includes(r.classCode),okW=p.wetDry==="ANY"||p.wetDry===r.wetDry,okP=!p.pregs.length||p.pregs.includes(r.preg);if(okC&&okW&&okP)return p.name}if(r.classCode==="S")return"Speyed cows";if(r.classCode==="B")return"Bulls";if(r.classCode==="C")return"Cull cows";return"Unallocated"}
function saveAnimal(){let r={...S.animal,station:S.active.station,year:S.active.year,paddock:S.active.paddock,mob:S.active.mob,date:S.active.date};r.draft=assignDraft(r);S.records.push(r);resetAnimal();completeSound();document.body.classList.remove("savedFlash");void document.body.offsetWidth;document.body.classList.add("savedFlash");save();renderCrush(`SAVED ✓ ${r.draft}`)}
function handleValue(v){if(!S.active)return;let af=activeFields(),idx=nextIdx();if(idx>=af.length){saveAnimal();return}let f=af[idx],val=f.val(String(v).toUpperCase());if(val===null){setStatus(`Invalid ${f.label}`,"error");errorSound();return}S.animal[f.k]=val;if(nextIdx()>=af.length)saveAnimal();else{beep(650,.05);renderCrush(`Recorded ${f.label}: ${f.disp(val)}`)}}
function renderCrush(msg="Ready"){headCount.textContent=S.records.length;animalNo.textContent=S.records.length+1;sessionBanner.textContent=S.active?`${S.active.station} | ${S.active.year} | ${S.active.paddock} | ${S.active.mob}`:"No active session";let idx=nextIdx(),af=S.active?activeFields():[];prompt.textContent=S.active?(idx>=af.length?"SAVED AUTOMATICALLY":af[idx].prompt):"START SESSION";fieldStack.innerHTML=af.map((f,i)=>{let val=S.animal[f.k],done=val!==null&&val!=="";let cls=done?"done":i===idx?"current":"";return `<div class="fieldBox ${cls}"><div class="fieldLabel">${f.label}</div><div class="fieldValue">${done?f.disp(val):f.hint}</div><div class="fieldIcon">${done?"✅":i===idx?"➡️":"⬜"}</div></div>`}).join("");setStatus(msg,"saved");let preg=S.records.filter(r=>r.preg&&r.preg!=="E").length,empty=S.records.filter(r=>r.preg==="E").length;livePreg.textContent=preg;liveEmpty.textContent=empty;livePregPct.textContent=pct(preg,S.records.length)+"%";let counts={};S.records.forEach(r=>counts[r.draft]=(counts[r.draft]||0)+1);let names=[...(S.active?.draftPens||[]).map(p=>p.name),"Unallocated","Speyed cows","Bulls","Cull cows"];draftBoard.innerHTML=[...new Set(names)].map(n=>`<div class="draftItem ${counts[n]?'draftHit':''}"><b>${counts[n]||0}</b> ${n}</div>`).join("");lastFive.innerHTML=S.records.slice(-5).reverse().map((r,i)=>`<div class="lastItem">#${S.records.length-i} ${classNames[r.classCode]||""} BCS ${r.bcs??"-"} ${r.preg??""} → ${r.draft}</div>`).join("")}
function setStatus(m,cls){status.textContent=m;status.className="status "+cls}
function finishSession(){if(!S.active)return;S.sessions.unshift({...S.active,records:[...S.records],finishedAt:new Date().toISOString()});S.active=null;S.records=[];save();completeSound();show("library")}
function undoLast(){if(S.records.length){S.records.pop();save();renderCrush("Undid last animal");errorSound()}}
quickInput.addEventListener("keydown",e=>{if(e.key==="F1"){e.preventDefault();undoLast();return}if(!S.active)return;let f=activeFields()[nextIdx()];if(!f)return;if(f.auto&&e.key.length===1){e.preventDefault();handleValue(e.key);quickInput.value=""}else if(!f.auto&&e.key==="Enter"){e.preventDefault();handleValue(quickInput.value);quickInput.value=""}});

function addTally(k){S.tally[k]=(S.tally[k]||0)+1;beep(700,.04);renderTally()}
function clearCurrentTally(){S.tally={};renderTally()}
function renderTally(){if(S.active){tyStation.value=S.active.station;tyYear.value=S.active.year;tyPaddock.value=S.active.paddock;tyMob.value=S.active.mob;tyTested.value=S.records.length;tyPregnant.value=S.records.filter(r=>r.preg&&r.preg!=="E").length}else tyYear.value ||= new Date().getFullYear();let total=Object.values(S.tally).reduce((a,b)=>a+b,0),cows=(S.tally["Wet cows"]||0)+(S.tally["Dry cows"]||0)+(S.tally["Cull cows"]||0)+(S.tally["Speyed cows"]||0),calves=S.tally.Calves||0,weaners=S.tally.Weaners||0;tallyOut.innerHTML=`<h3>Current tally: ${total} head</h3><table class="table"><tr><th>Class</th><th>Head</th></tr>${Object.keys(S.tally).sort().map(k=>`<tr><td>${k}</td><td>${S.tally[k]}</td></tr>`).join("")}</table><p>Calving/branding estimate: ${pct(calves,cows)}%. Weaning estimate: ${pct(weaners,cows)}%.</p>`}
function saveTally(){let t={id:uid(),station:tyStation.value||"Unnamed Station",year:+tyYear.value||new Date().getFullYear(),paddock:tyPaddock.value,mob:tyMob.value,joined:+tyJoined.value||0,tested:+tyTested.value||0,pregnant:+tyPregnant.value||0,notes:tyNotes.value,counts:{...S.tally},date:new Date().toISOString()};S.tallies.unshift(t);S.tally={};save();completeSound();renderTally()}

function benchmark(country){return {"Northern Forest":{preg:70,wean:55,lowBcs:25},"Northern Downs":{preg:80,wean:70,lowBcs:20},"Central Forest":{preg:82,wean:72,lowBcs:18},"Southern Forest":{preg:85,wean:75,lowBcs:15},"Mixed / Other":{preg:80,wean:70,lowBcs:20}}[country||"Mixed / Other"]}
function projectionRows(records){let p=profile(S.active?.station)||{},target=p.targetBcs||3;let groups=[["Maiden heifers",r=>r.classCode==="H",p.heiferGrowth||0,p.dryBcs||0],["First-lactation heifers",r=>r.classCode==="F",p.heiferGrowth||0,p.wetBcs||0],["Wet cows",r=>r.classCode==="W"||r.wetDry==="Wet",p.cowGrowth||0,p.wetBcs||0],["Dry cows",r=>r.classCode==="D"||r.wetDry==="Dry",p.cowGrowth||0,p.dryBcs||0]];return groups.map(g=>{let x=records.filter(g[1]),aw=avg(x.map(r=>r.weight)),ab=avg(x.map(r=>r.bcs));return {name:g[0],n:x.length,aw,projW:aw?aw+g[2]:null,ab,projB:ab?Math.max(1,Math.min(5,ab+g[3])):null,below:pct(x.filter(r=>r.bcs&&r.bcs<target).length,x.length),pub:p.puberty&&aw?aw+g[2]>=p.puberty:null}}).filter(x=>x.n)}
function calvDist(records){let o={};records.filter(r=>r.preg&&r.preg!=="E").forEach(r=>{let w=calvingWindow(r.preg,S.active?.date||today());o[w]=(o[w]||0)+1});return o}
function renderReport(){let rec=S.records.length?S.records:(S.sessions[0]?.records||[]);if(!rec.length){reportSummary.innerHTML="No current or saved session selected.";return}let session=S.active||S.sessions[0],p=profile(session.station),b=benchmark(p?.country);let preg=rec.filter(r=>r.preg&&r.preg!=="E").length,empty=rec.filter(r=>r.preg==="E").length,low=pct(rec.filter(r=>r.bcs&&r.bcs<=(p?.targetBcs||3)-1).length,rec.length);reportSummary.innerHTML=`<h3>${session.station} — ${session.year} — ${session.paddock} — ${session.mob}</h3><p>Total ${rec.length}; Pregnant ${preg} (${pct(preg,rec.length)}%); Empty ${empty}; Low BCS risk ${low}%.</p>`;profileCard.innerHTML=p?profileHTML(p):"No station profile.";kpiCard.innerHTML=`<h3>North Australia KPI checks</h3><p>Pregnancy: ${pct(preg,rec.length)}% vs benchmark ${b.preg}%.</p><p>Low BCS: ${low}% vs target max ${b.lowBcs}%.</p><p>${riskText(p||{})}</p>`;let rows=projectionRows(rec);forecastCard.innerHTML=`<h3>12 month forecast</h3><table class="table"><tr><th>Group</th><th>Head</th><th>Wt now</th><th>Wt 12m</th><th>BCS now</th><th>BCS 12m</th><th>Puberty</th></tr>${rows.map(r=>`<tr><td>${r.name}</td><td>${r.n}</td><td>${r.aw?r.aw.toFixed(0):"N/A"}</td><td>${r.projW?r.projW.toFixed(0):"N/A"}</td><td>${r.ab?r.ab.toFixed(1):"N/A"}</td><td>${r.projB?r.projB.toFixed(1):"N/A"}</td><td>${r.pub===null?"N/A":r.pub?"On track":"Below target"}</td></tr>`).join("")}</table>`;drawCharts(rec,rows,b)}
function clearCharts(){charts.forEach(c=>c.destroy());charts=[]}
function chart(id,type,labels,datasets){charts.push(new Chart($(id),{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,scales:type==="bar"?{y:{beginAtZero:true}}:{}}}))}
function drawCharts(rec,rows,b){clearCharts();let cls=["H","F","W","D","C","S","B"];chart("chartPregClass","bar",cls.map(c=>classNames[c]),[{label:"Preg %",data:cls.map(c=>{let x=rec.filter(r=>r.classCode===c);return pct(x.filter(r=>r.preg&&r.preg!=="E").length,x.length)})}]);let stages=["E","P1","P2","P3","P4","P5","P6","P7","P8","P9"];chart("chartStage","bar",stages,[{label:"Head by preg stage",data:stages.map(s=>rec.filter(r=>r.preg===s).length)}]);chart("chartSeason","bar",["In-season est P1-P6","Out-of-season est P7-P9"],[{label:"%",data:[pct(rec.filter(r=>pregNo(r.preg)>=1&&pregNo(r.preg)<=6).length,rec.filter(r=>r.preg&&r.preg!=="E").length),pct(rec.filter(r=>pregNo(r.preg)>=7).length,rec.filter(r=>r.preg&&r.preg!=="E").length)]}]);chart("chartBCS","bar",["1","2","3","4","5"],[{label:"Preg % by BCS",data:[1,2,3,4,5].map(v=>{let x=rec.filter(r=>r.bcs===v);return pct(x.filter(r=>r.preg&&r.preg!=="E").length,x.length)})}]);let bands=["<300","300-349","350-399","400-449","450+"];let band=w=>w<300?"<300":w<350?"300-349":w<400?"350-399":w<450?"400-449":"450+";let h=rec.filter(r=>["H","F"].includes(r.classCode)&&r.weight);chart("chartHeiferWeight","bar",bands,[{label:"Heifer preg % by weight",data:bands.map(bb=>{let x=h.filter(r=>band(r.weight)===bb);return pct(x.filter(r=>r.preg&&r.preg!=="E").length,x.length)})}]);let cd=calvDist(rec);chart("chartCalving","bar",Object.keys(cd),[{label:"Expected calvings",data:Object.values(cd)}]);chart("chartProjection","bar",rows.map(r=>r.name),[{label:"Weight now",data:rows.map(r=>r.aw||0)},{label:"Projected 12m",data:rows.map(r=>r.projW||0)}]);chart("chartBenchmark","bar",["Preg %","Low BCS max"],[{label:"This session",data:[pct(rec.filter(r=>r.preg&&r.preg!=="E").length,rec.length),pct(rec.filter(r=>r.bcs&&r.bcs<=2).length,rec.length)]},{label:"Benchmark",data:[b.preg,b.lowBcs]}]);let t=S.tallies.filter(x=>x.station===(S.active?.station||S.sessions[0]?.station));chart("chartProduction","bar",t.map(x=>`${x.year} ${x.mob}`),[{label:"Weaning %",data:t.map(x=>pct(x.counts.Weaners||0,x.joined||x.pregnant))},{label:"Calving/branding %",data:t.map(x=>pct(x.counts.Calves||0,x.joined||x.pregnant))}])}
function renderLibrary(){let names=[...new Set([...S.profiles.map(p=>p.name),...S.sessions.map(s=>s.station),...S.tallies.map(t=>t.station)])];libraryOut.innerHTML=names.sort().map(n=>{let prof=profile(n),sessions=S.sessions.filter(s=>s.station===n),tallies=S.tallies.filter(t=>t.station===n);let years=[...new Set([...sessions.map(s=>s.year),...tallies.map(t=>t.year)])].sort((a,b)=>b-a);return `<div class="panel"><h3>📁 ${n}</h3>${prof?`<div class="row">Profile: ${prof.country} ${prof.total||"?"} cattle <button onclick="App.openProfile('${prof.id}')">Open</button></div>`:""}${years.map(y=>`<div class="row"><b>📂 ${y}</b> ${sessions.filter(s=>s.year==y).length} preg sessions, ${tallies.filter(t=>t.year==y).length} tallies</div>`).join("")}</div>`}).join("")||"No station data yet."}
function exportCSV(){let rows=[["Station","Year","Paddock","Mob","Class","Age","BCS","Preg","Weight","WetDry","Draft"]];S.records.forEach(r=>rows.push([r.station,r.year,r.paddock,r.mob,classNames[r.classCode]||r.classCode,r.age??"",r.bcs??"",r.preg??"",r.weight??"",r.wetDry??"",r.draft]));let csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="station_stats_records.csv";a.click()}
function beep(f,d=.08){try{let c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator();o.connect(c.destination);o.frequency.value=f;o.start();o.stop(c.currentTime+d)}catch(e){}}
function completeSound(){beep(900,.12);setTimeout(()=>beep(1250,.14),140)}
function errorSound(){beep(220,.15)}
function clearAll(){if(confirm("Clear all local data?")){localStorage.removeItem(KEY);location.reload()}}
load();ssDate.value=today();ssYear.value=new Date().getFullYear();tyYear.value=new Date().getFullYear();renderDraftTemplates();renderDraftPens();
return {show,saveProfile,openProfile,applyProfileToSession,addDraftPen,removeDraftPen,clearDraftPens,loadDraftExample,saveDraftTemplate,loadDraftTemplate,renderCalvingGuide,startSession,finishSession,addTally,clearCurrentTally,saveTally,renderLibrary,renderReport,exportCSV,clearAll}
})();