const App=(()=>{const KEY="CVSS_V30";
const classNames={H:"Maiden heifer",F:"First-lactation heifer",W:"Wet cow",D:"Dry cow",C:"Cull cow",S:"Speyed cow",B:"Bull"};
const pregStages=["E","P1","P2","P3","P4","P5","P6","P7","P8","P9"];
const bcsStages=["1","2","3","4","5"];
const yardClasses=["Calves","Weaners","Maiden heifers","First-lactation heifers","Wet cows","Dry cows","Cull cows","Speyed cows","Bulls","Mickies","Steers"];
let S={jobs:[],active:null,records:[],draftPens:[],animal:{},mob:{preg:{},bcs:{},other:{}},yard:{}};let charts=[];
const $=id=>document.getElementById(id), uid=()=>crypto.randomUUID(), today=()=>new Date().toISOString().slice(0,10);
const pct=(n,d)=>d?Math.round(n/d*100):0; const avg=a=>{let v=a.filter(x=>x!=null&&!isNaN(x));return v.length?v.reduce((x,y)=>x+y,0)/v.length:null}; const pregNo=p=>!p||p==="E"?0:Number(String(p).replace("P",""));
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function load(){let r=localStorage.getItem(KEY);if(r)S=JSON.parse(r);S.jobs??=[];S.records??=[];S.draftPens??=[];S.mob??={preg:{},bcs:{},other:{}};S.yard??={}}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");if(id==="home")renderHome();if(id==="mob")renderMob();if(id==="yard")renderYard();if(id==="crush"){renderCrush();setTimeout(()=>quickInput.focus(),50)}if(id==="report")renderReport();if(id==="history")renderHistory();if(id==="setup"){renderDraftPens();renderCalvingGuide();}}
function renderHome(){let last=S.jobs[0];homeOut.innerHTML=`<p>${S.active?`<b>Active:</b> ${S.active.station} / ${S.active.mob} / ${S.active.type}`:"No active job."}</p><p>${last?`<b>Last job:</b> ${last.station} ${last.year} / ${last.paddock} / ${last.mob}`:"No saved jobs yet."}</p><p><b>Best daily workflow:</b> New job → Mob Sheet or Crush Mode → Yard Tally totals → Finish → Report.</p>`}
function quickJob(type){show("setup");setJobType(type)}
function repeatLastJob(){let j=S.jobs[0];if(!j){alert("No previous job.");return}show("setup");jobType.value=j.type;jobStation.value=j.station;jobYear.value=j.year;jobDate.value=today();jobPaddock.value=j.paddock;jobMob.value=j.mob;jobVet.value=j.vet;jobRecorder.value=j.recorder;S.draftPens=JSON.parse(JSON.stringify(j.draftPens||[]));renderDraftPens()}
function setJobType(type){jobType.value=type;if(type==="mob"){recClass.checked=false;recAge.checked=false;recBCS.checked=false;recPreg.checked=true;recWeight.checked=false;recWetDry.checked=false}else if(type==="crush"){recClass.checked=true;recAge.checked=true;recBCS.checked=true;recPreg.checked=true;recWeight.checked=false;recWetDry.checked=true}else{recClass.checked=false;recAge.checked=false;recBCS.checked=false;recPreg.checked=false;recWeight.checked=false;recWetDry.checked=false}}
function startJob(){S.active={id:uid(),type:jobType.value,station:jobStation.value||"Unnamed Station",year:+jobYear.value||new Date().getFullYear(),date:jobDate.value||today(),paddock:jobPaddock.value,mob:jobMob.value,vet:jobVet.value,recorder:jobRecorder.value,recClass:recClass.checked,recAge:recAge.checked,recBCS:recBCS.checked,recPreg:recPreg.checked,recWeight:recWeight.checked,recWetDry:recWetDry.checked,draftPens:JSON.parse(JSON.stringify(S.draftPens))};S.records=[];S.mob={preg:{},bcs:{},other:{}};S.yard={};resetAnimal();save();if(S.active.type==="crush")show("crush");else if(S.active.type==="yard")show("yard");else show("mob")}
function finishJob(){if(!S.active)return;S.jobs.unshift({...S.active,records:[...S.records],mob:JSON.parse(JSON.stringify(S.mob)),yard:JSON.parse(JSON.stringify(S.yard)),finishedAt:new Date().toISOString()});S.active=null;S.records=[];completeSound();save();show("report")}
function selected(id){return Array.from($(id).selectedOptions).map(o=>o.value)}
function addDraftPen(){let p={id:uid(),name:draftName.value||`Pen ${S.draftPens.length+1}`,classes:selected("draftClasses"),wetDry:draftWetDry.value,pregs:selected("draftPregs")};S.draftPens.push(p);draftName.value="";save();renderDraftPens()}
function removeDraftPen(id){S.draftPens=S.draftPens.filter(p=>p.id!==id);save();renderDraftPens()}
function clearDraftPens(){S.draftPens=[];save();renderDraftPens()}
function loadDraftExample(type){S.draftPens=type==="heifers"?[{id:uid(),name:"Pen 1 - Empty heifers",classes:["H","F"],wetDry:"ANY",pregs:["E"]},{id:uid(),name:"Pen 2 - P1-P3 heifers",classes:["H","F"],wetDry:"ANY",pregs:["P1","P2","P3"]},{id:uid(),name:"Pen 3 - P4-P6 heifers",classes:["H","F"],wetDry:"ANY",pregs:["P4","P5","P6"]},{id:uid(),name:"Pen 4 - P7-P9 heifers",classes:["H","F"],wetDry:"ANY",pregs:["P7","P8","P9"]}]:[{id:uid(),name:"Pen 1 - Wet empty + dry P8-P9",classes:["W","D"],wetDry:"ANY",pregs:["E","P8","P9"]},{id:uid(),name:"Pen 2 - Dry P1-P6",classes:["D"],wetDry:"ANY",pregs:["P1","P2","P3","P4","P5","P6"]},{id:uid(),name:"Pen 3 - Wet P1-P7",classes:["W"],wetDry:"ANY",pregs:["P1","P2","P3","P4","P5","P6","P7"]},{id:uid(),name:"Pen 4 - Speyed/bulls/culls",classes:["S","B","C"],wetDry:"ANY",pregs:[]}];save();renderDraftPens()}
function renderDraftPens(){if(!window.draftPens)return;draftPens.innerHTML=S.draftPens.length?S.draftPens.map((p,i)=>`<div class="draftPenItem"><b>${i+1}. ${p.name}</b><br>Class: ${p.classes.map(c=>classNames[c]).join(", ")||"Any"}<br>Wet/Dry: ${p.wetDry}; Preg: ${p.pregs.join(", ")||"Any"} <button onclick="App.removeDraftPen('${p.id}')">Remove</button></div>`).join(""):"No draft pens selected."}
function addMonths(d,m){let x=new Date(d);x.setMonth(x.getMonth()+m);return x} function mon(d){return d.toLocaleDateString("en-AU",{month:"short",year:"numeric"})} function calvingWindow(p){if(p==="E")return"Empty";let m=Math.max(0,10-pregNo(p));return `${mon(addMonths(jobDate.value||today(),m))}–${mon(addMonths(jobDate.value||today(),m+1))}`}
function renderCalvingGuide(){if(!window.calvingGuide)return;calvingGuide.innerHTML="<h4>Calving guide</h4>"+pregStages.map(p=>`<div><b>${p}</b>: ${calvingWindow(p)}</div>`).join("")}
function countControl(label,val,onchange){return `<div class="countRow"><label>${label}</label><input type="number" min="0" value="${val||0}" onchange="${onchange}"><button onclick="${onchange.replace('this.value','Number(this.previousElementSibling.value)+1')}">+</button></div>`}
function renderMob(){if(!S.active){mobBanner.textContent="No active mob job.";return}mobBanner.textContent=`${S.active.station} | ${S.active.paddock} | ${S.active.mob} | ${S.active.date}`;pregInputs.innerHTML=pregStages.map(p=>countControl(p,S.mob.preg[p],`App.setMobPreg('${p}',this.value)`)).join("");bcsInputs.innerHTML=bcsStages.map(b=>countControl("BCS "+b,S.mob.bcs[b],`App.setMobBCS('${b}',this.value)`)).join("");let others=["Wet cows","Dry cows","CFA / cull cows","Speyed cows","Bulls","Mickies","Steers"];otherInputs.innerHTML=others.map(o=>countControl(o,S.mob.other[o],`App.setMobOther('${o}',this.value)`)).join("");renderMobSummary()}
function setMobPreg(k,v){S.mob.preg[k]=+v||0;save();renderMobSummary()} function setMobBCS(k,v){S.mob.bcs[k]=+v||0;save();renderMobSummary()} function setMobOther(k,v){S.mob.other[k]=+v||0;save();renderMobSummary()}
function renderMobSummary(){let totalPreg=Object.values(S.mob.preg).reduce((a,b)=>a+(+b||0),0),preg=totalPreg-(S.mob.preg.E||0);mobSummary.innerHTML=`<h3>Mob summary</h3><p>Total preg records: ${totalPreg}; Pregnant: ${preg} (${pct(preg,totalPreg)}%); Empty: ${S.mob.preg.E||0}.</p><p>In-season est P1-P6: ${pct(["P1","P2","P3","P4","P5","P6"].reduce((a,k)=>a+(S.mob.preg[k]||0),0),preg)}%. Out-of-season/early est P7-P9: ${pct(["P7","P8","P9"].reduce((a,k)=>a+(S.mob.preg[k]||0),0),preg)}%.</p>`}
function renderYard(){yardInputs.innerHTML=yardClasses.map(c=>`<label>${c}<input type="number" min="0" value="${S.yard[c]||0}" oninput="App.setYard('${c}',this.value)"></label>`).join("");renderYardSummary()} function setYard(k,v){S.yard[k]=+v||0;save();renderYardSummary()} function renderYardSummary(){let total=Object.values(S.yard).reduce((a,b)=>a+(+b||0),0),cows=(S.yard["Wet cows"]||0)+(S.yard["Dry cows"]||0)+(S.yard["Cull cows"]||0)+(S.yard["Speyed cows"]||0),calves=S.yard.Calves||0,weaners=S.yard.Weaners||0;yardSummary.innerHTML=`<h3>Yard tally</h3><p>Total: ${total}. Calving/branding estimate: ${pct(calves,cows)}%. Weaning estimate: ${pct(weaners,cows)}%.</p>`}
const fields=[{k:"classCode",label:"CLASS",on:s=>s.recClass,prompt:"ENTER CLASS",hint:"H/F/W/D/C/S/B",auto:true,val:v=>["H","F","W","D","C","S","B"].includes(v)?v:null,disp:v=>classNames[v]},{k:"age",label:"AGE",on:s=>s.recAge,prompt:"ENTER AGE",hint:"0-9",auto:true,val:v=>/^[0-9]$/.test(v)?+v:null,disp:v=>v},{k:"bcs",label:"BCS",on:s=>s.recBCS,prompt:"ENTER BCS",hint:"1-5",auto:true,val:v=>/^[1-5]$/.test(v)?+v:null,disp:v=>v},{k:"preg",label:"PREG",on:s=>s.recPreg,prompt:"ENTER PREG",hint:"E/1-9",auto:true,val:v=>v==="E"?"E":/^[1-9]$/.test(v)?"P"+v:null,disp:v=>v},{k:"weight",label:"WEIGHT",on:s=>s.recWeight,prompt:"ENTER WEIGHT",hint:"kg + Enter",auto:false,val:v=>+v>0?+v:null,disp:v=>v+"kg"},{k:"wetDry",label:"WET/DRY",on:s=>s.recWetDry,prompt:"ENTER WET/DRY",hint:"W/D",auto:true,val:v=>["W","WET"].includes(v)?"Wet":["D","DRY"].includes(v)?"Dry":null,disp:v=>v}];
function af(){return fields.filter(f=>f.on(S.active))} function resetAnimal(){S.animal={id:uid()}} function nextIdx(){let a=af();for(let i=0;i<a.length;i++)if(S.animal[a[i].k]==null||S.animal[a[i].k]==="")return i;return a.length}
function assignDraft(r){for(let p of S.active.draftPens||[]){let okC=!p.classes.length||p.classes.includes(r.classCode),okW=p.wetDry==="ANY"||p.wetDry===r.wetDry,okP=!p.pregs.length||p.pregs.includes(r.preg);if(okC&&okW&&okP)return p.name}return"Unallocated"}
function saveAnimal(){let r={...S.animal,station:S.active.station,year:S.active.year,paddock:S.active.paddock,mob:S.active.mob,date:S.active.date};r.draft=assignDraft(r);S.records.push(r);resetAnimal();completeSound();document.body.classList.remove("savedFlash");void document.body.offsetWidth;document.body.classList.add("savedFlash");save();renderCrush("SAVED ✓ "+r.draft)}
function handleValue(v){let a=af(),i=nextIdx();if(i>=a.length){saveAnimal();return}let f=a[i],val=f.val(String(v).toUpperCase());if(val==null){status.textContent="Invalid "+f.label;status.className="status error";errorSound();return}S.animal[f.k]=val;if(nextIdx()>=a.length)saveAnimal();else renderCrush("Recorded "+f.label)}
function renderCrush(msg="Ready"){if(!S.active)return;let a=af(),i=nextIdx();animalNo.textContent=S.records.length+1;prompt.textContent=i>=a.length?"SAVED":a[i].prompt;fieldStack.innerHTML=a.map((f,idx)=>{let v=S.animal[f.k],done=v!=null&&v!=="";return `<div class="fieldBox ${done?'done':idx===i?'current':''}"><div class="fieldLabel">${f.label}</div><div class="fieldValue">${done?f.disp(v):f.hint}</div><div class="fieldIcon">${done?'✅':idx===i?'➡️':'⬜'}</div></div>`}).join("");status.textContent=msg;status.className="status saved";headCount.textContent=S.records.length;let preg=S.records.filter(r=>r.preg&&r.preg!="E").length;livePreg.textContent=preg;livePregPct.textContent=pct(preg,S.records.length)+"%";let dc={};S.records.forEach(r=>dc[r.draft]=(dc[r.draft]||0)+1);draftBoard.innerHTML=[...new Set([...(S.active.draftPens||[]).map(p=>p.name),"Unallocated"])].map(n=>`<div class="draftItem ${dc[n]?'draftHit':''}"><b>${dc[n]||0}</b> ${n}</div>`).join("");lastFive.innerHTML=S.records.slice(-5).reverse().map((r,idx)=>`<div class="lastItem">#${S.records.length-idx} ${classNames[r.classCode]||""} ${r.preg||""} → ${r.draft}</div>`).join("")}
quickInput.addEventListener("keydown",e=>{if(e.key==="F1"){e.preventDefault();S.records.pop();renderCrush("Undid last");return}if(!S.active)return;let f=af()[nextIdx()];if(!f)return;if(f.auto&&e.key.length===1){e.preventDefault();handleValue(e.key);quickInput.value=""}else if(!f.auto&&e.key==="Enter"){e.preventDefault();handleValue(quickInput.value);quickInput.value=""}});
function latest(){return S.active||S.jobs[0]} function merged(job){job=job||latest();let mob=job?.mob||S.mob,yard=job?.yard||S.yard,records=job?.records||S.records;let preg={...mob.preg};records.forEach(r=>{if(r.preg)preg[r.preg]=(preg[r.preg]||0)+1});let bcs={...mob.bcs};records.forEach(r=>{if(r.bcs)bcs[r.bcs]=(bcs[r.bcs]||0)+1});let classes={...yard};records.forEach(r=>{let k=r.classCode==="H"?"Maiden heifers":r.classCode==="F"?"First-lactation heifers":r.classCode==="W"?"Wet cows":r.classCode==="D"?"Dry cows":r.classCode==="C"?"Cull cows":r.classCode==="S"?"Speyed cows":r.classCode==="B"?"Bulls":null;if(k)classes[k]=(classes[k]||0)+1});return{preg,bcs,classes,records}}
function renderReport(){let job=latest();if(!job){reportSummary.innerHTML="No job yet.";return}let m=merged(job),total=Object.values(m.preg).reduce((a,b)=>a+(+b||0),0),preg=total-(m.preg.E||0);reportSummary.innerHTML=`<h3>${job.station} — ${job.year} — ${job.paddock} — ${job.mob}</h3><p>Total preg count ${total}; Pregnant ${preg} (${pct(preg,total)}%); Empty ${m.preg.E||0}.</p>`;kpiCard.innerHTML=`<h3>Key KPIs</h3><p>In-season est P1-P6: ${pct(["P1","P2","P3","P4","P5","P6"].reduce((a,k)=>a+(m.preg[k]||0),0),preg)}%.</p><p>Out-of-season/early est P7-P9: ${pct(["P7","P8","P9"].reduce((a,k)=>a+(m.preg[k]||0),0),preg)}%.</p>`;forecastCard.innerHTML=`<h3>Calving forecast</h3><table class="table"><tr><th>Stage</th><th>Head</th><th>Expected calving</th></tr>${pregStages.filter(p=>p!="E").map(p=>`<tr><td>${p}</td><td>${m.preg[p]||0}</td><td>${calvingWindow(p)}</td></tr>`).join("")}</table>`;advisoryCard.innerHTML=`<h3>Veterinary advisory</h3><p>${pct(m.preg.E||0,total)>15?'<span class="bad">High empty rate: review nutrition, bulls, vibriosis/pestivirus and joining management.</span>':'<span class="good">Empty rate not excessive from current inputs.</span>'}</p><p>${(m.bcs["1"]||0)+(m.bcs["2"]||0)>0?'<span class="warn">BCS 1–2 animals present: consider nutrition/lactation management and early weaning options.</span>':'BCS risk data limited or acceptable.'}</p>`;mergedCard.innerHTML=`<h3>Merged mob + crush + yard tally</h3><table class="table"><tr><th>Class</th><th>Head</th></tr>${Object.keys(m.classes).map(k=>`<tr><td>${k}</td><td>${m.classes[k]}</td></tr>`).join("")}</table>`;drawCharts(m)}
function clearCharts(){charts.forEach(c=>c.destroy());charts=[]} function chart(id,type,labels,datasets){charts.push(new Chart($(id),{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,scales:type==="bar"?{y:{beginAtZero:true}}:{}}}))}
function drawCharts(m){clearCharts();chart("chartPreg","bar",pregStages,[{label:"Preg stage",data:pregStages.map(p=>m.preg[p]||0)}]);chart("chartBCS","bar",bcsStages,[{label:"BCS",data:bcsStages.map(b=>m.bcs[b]||0)}]);let cd={};pregStages.filter(p=>p!="E").forEach(p=>cd[calvingWindow(p)]=(cd[calvingWindow(p)]||0)+(m.preg[p]||0));chart("chartCalving","bar",Object.keys(cd),[{label:"Expected calvings",data:Object.values(cd)}]);chart("chartMerged","bar",Object.keys(m.classes),[{label:"Class tally",data:Object.values(m.classes)}]);let dc={};m.records.forEach(r=>dc[r.draft]=(dc[r.draft]||0)+1);chart("chartDraft","bar",Object.keys(dc),[{label:"Drafts",data:Object.values(dc)}]);let pregTotal=Object.values(m.preg).reduce((a,b)=>a+(+b||0),0),preg=pregTotal-(m.preg.E||0);chart("chartBench","bar",["Preg %","Empty %"],[{label:"This mob",data:[pct(preg,pregTotal),pct(m.preg.E||0,pregTotal)]},{label:"Target",data:[82,10]}])}
function renderHistory(){historyOut.innerHTML=S.jobs.map(j=>`<div class="panel"><h3>${j.station} ${j.year}</h3><p>${j.type} — ${j.paddock} / ${j.mob} — ${j.date}</p></div>`).join("")||"No saved jobs yet."}
function exportCSV(){let job=latest(),m=merged(job),rows=[["Type","Category","Value"]];Object.keys(m.preg).forEach(k=>rows.push(["Preg",k,m.preg[k]]));Object.keys(m.bcs).forEach(k=>rows.push(["BCS",k,m.bcs[k]]));Object.keys(m.classes).forEach(k=>rows.push(["Class",k,m.classes[k]]));let csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="station_stats_v3_report.csv";a.click()}
function beep(f,d=.08){try{let c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator();o.connect(c.destination);o.frequency.value=f;o.start();o.stop(c.currentTime+d)}catch(e){}} function completeSound(){beep(900,.12);setTimeout(()=>beep(1250,.14),140)} function errorSound(){beep(220,.15)}
function clearAll(){if(confirm("Clear all local Station Stats data?")){localStorage.removeItem(KEY);location.reload()}}
load();jobDate.value=today();jobYear.value=new Date().getFullYear();renderHome();
return{show,quickJob,repeatLastJob,setJobType,startJob,finishJob,addDraftPen,removeDraftPen,clearDraftPens,loadDraftExample,renderCalvingGuide,setMobPreg,setMobBCS,setMobOther,setYard,renderHistory,renderReport,exportCSV,clearAll}
})();